---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-s3
  namespace: kube-system
  labels:
    k8s-app: fluentd-s3
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-s3
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd-s3
        image: fenglixa/pipeline-logs-s3:latest
        imagePullPolicy: Always
        # env:
        # - name: S3_LOGS_BUCKET_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kubernetes-fluentd-s3-config
        #       key: S3_LOGS_BUCKET_NAME
        # - name: S3_LOGS_BUCKET_PREFIX
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kubernetes-fluentd-s3-config
        #       key: S3_LOGS_BUCKET_PREFIX
        # - name: S3_LOGS_BUCKET_REGION
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kubernetes-fluentd-s3-config
        #       key: S3_LOGS_BUCKET_REGION
        args:
          - --use-v1-config
          - -vv
          # --use-v1-config allows using env vars in config file
          # -qq sets fluentd log level to ERROR, -v: debug, -vv: trace
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
